config/routes.rb
Rails.application.routes.draw do

  root 'homepage#show'
  get 'books' => 'books#index', as: :books
  get 'books/new' => 'books#new', as: :new_book
  get 'books/:id' => 'books#show', as: :book
  post 'books' => 'books#create'
  get 'books/:id/edit' => 'books#edit', as: :edit_book
  patch "books/:id" => 'books#update'
  delete "books/:id" => 'books#delete'
  get 'authors' => 'authors#index', as: :authors
  get 'authors/new' => 'authors#new', as: :new_author
  get 'authors/:id' => 'authors#show', as: :author
  post 'authors' => 'authors#create'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  validates :first_name, :last_name, presence: true

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  attachment :photo
    validates :title, :author, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
    @books = Book.all
  end

  def show
    @author = Author.find_by id: params[:id]
  end

  def new
    @author = Author.new
  end

  def create
    # instantiate
    @author = Author.new
    # set values
    @author.first_name = params[:author][:first_name]
    @author.last_name = params[:author][:last_name]
    @author.authorbio = params[:author][:authorbio]
    # save
    if @author.save
      redirect_to "/authors"
    else
      render :new
    end
    # redirect or render form
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    # instantiate a blank Book object
    @book = Book.new
    # set the values
    @book.title = params[:book][:title]
    @book.author_id = params[:book][:author_id]
    @book.price = params[:book][:price]
    # save it
    if @book.save
      # redirect to "/books"
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find_by id: params[:id]
  end

  def update
    # instantiant / Find
    @book = Book.find_by id: params[:id]
    # set values
    @book.title = params[:book][:title]
    @book.author_id = params[:book][:author_id]
    @book.price = params[:book][:price]
    @book.photo = params[:book][:photo]
    
    # save it
    if @book.save
      # redirect to "/books"
      redirect_to book_path(id: @book.id)
    else
      render :edit
    end
  end

  def delete
    @book = Book.find_by id: params[:id]
    @book.destroy
    redirect_to books_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table class="table">
  <thead>
    <tr>
      <th>
        Last Name
      </th>
      <th>
        First Name
      </th>
      <th>
        Details
      </th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td>
          <%= author.first_name %>
        </td>
        <td>
          <%= author.last_name %>
        </td>
        <td>
          <%= link_to "View Details", "/authors/#{author.id}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<div class="page-header">
  <h1>New Author</h1>

</div>

<% if @author.errors.any? %>
  <% @author.errors.full_messages.each do |error| %>
    <p class="alert alert-danger"><strong><%= error %></strong></p>
  <% end %>
<% end %>

<%= form_for @author, url: "/authors" do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :authorbio %>
    <%= f.text_field :authorbio, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.full_name %></h1>
<h3><%= @author.authorbio %></h3>
<h3>Books</h3>

<ul>
  <% @author.books.each do |book| %>
    <li><%= book.title %></li>
  <% end %>
</ul>

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |error| %>
    <p class="alert alert-danger"><strong><%= error %></strong></p>
  <% end %>
<% end %>

<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.collection_select :author_id, Author.all, :id, :full_name, {prompt: true},  {class: "form-control"} %>
  </div>


  <div class="form-group">
    <%= f.label :photo %>
    <%= f.attachment_field :photo, class: "" %>
    <% if @book.errors[:photo].any? %>
      <span class="mdl-textfield__error">* <%= @book.errors[:photo].join(", ") %> </span>
    <% end %>
  </div>


  <div class="">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/books/edit.html.erb
<div class="page-header">
  <h1>Edit <%= @book.title %></h1>
</div>
<%= render partial: 'form' %>

app/views/books/index.html.erb
<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th>
        Title
      </th>
      <th>
        Author
      </th>
      <th>
        Details
      </th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= book.title %>
        </td>
        <td>
          <%= book.author.first_name %> <%= book.author.last_name %>
        </td>
        <td>
          <div class="bookndx">
            <%= link_to "View Details ", book_path(id: book.id) %>
          </div>
        </td>
        <td>
          <div class="pricendx">
            <%= " $ " %><%= " " %><%= book.price %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<div class="page-header">
  <h1>New Book <small></small></h1>
</div>

<%= render partial: 'form' %>

app/views/books/show.html.erb
<h1><%= @book.title %><p><%='-:-'%></p><small><%= @book.author.first_name %> <%= @book.author.last_name %></small></h1>
<div class = "lonecontainer">
  <%= image_tag attachment_url(@book, :photo, :fill, 500, 625, format: "jpg") %>
</div>
<%= link_to "Edit", edit_book_path(id: @book.id), class: "btn btn-default"%>
<%= link_to "Delete", book_path(id: @book.id), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete?"}%>

app/views/homepage/show.html.erb
<h1>THE IRONLIBRARY</h1>
<div class="wrapper">
  <div class="datewrapper">
    <p>18MAR2016 last update</p>
  </div>
</div>
<div class="listbooks">
  <%= link_to "List Books", books_path, class: "btn btn-success btn-lg btn-block" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ironlibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Acme' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
</head>
<body>
  <header>
    <nav>
      <%= link_to "Home", root_path %>
      <%= link_to "Books", books_path %>
      <%= link_to "New Book", new_book_path %>
      <%= link_to "Authors", authors_path %>
      <%= link_to "New Author", new_author_path %>
    </nav>
  </header>

    <%= yield %>

</body>
</html>